angular.module("myApp",["ngRoute"])
.config(["$routeProvider","$rootScope","$location",function($routeProvider,$rootScope,$location){
      $routeProvider
      .when("/login",{templateUrl:"script/view/login.html",controller:'myCtrl'})
        .when("/main",{templateUrl:"script/view/home.html",controller:'myLogoutCtrl'})
          .when("/4",{templateUrl:"http://www.w3schools.com/angular/main.htm"})
          .when("/4",{templateUrl:"http://www.w3schools.com/angular/main.htm"})
          .otherwise({
            redirectTo:"/login"
          });
    }])
